((nil . ((fill-column . 80)))
 (verilog-mode . ((verilog-indent-level . 2)
                  (verilog-indent-level-behavioral . 2)
                  (verilog-indent-level-declaration . 2)
                  (verilog-indent-level-module . 0)
                  (verilog-auto-lineup . all))))
